### ISSUE TITLE
Build failure seen with block overrun error

### ISSUE THREAD

**Issue by namrata-ibm** [AdoptOpenJDK/openjdk8-openj9-releases#3]
While building TensorFlow from source on s390x Ubuntu 16.04 with AdoptJDK facing below error:
```
bazel build -c opt //tensorflow/tools/pip_package:build_pip_package  
.
.
.
ERROR: /root/tensorflow/tensorflow/tools/pip_package/BUILD:117:1: no such package '@nasm//': java.io.IOException: block overrun and referenced by '//tensorflow/tools/pip_package:licenses'
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: no such package '@nasm//': java.io.IOException: block overrun
INFO: Elapsed time: 14.837s
FAILED: Build did NOT complete successfully (137 packages loaded)
    currently loading: tensorflow/core/kernels ... (2 packages)
```
It seems this is related to AdoptOpenJDK on s390x. I have verified that the build with OpenJDK 8 works.
Further, verified the `nasm` file is valid. More discussion can be found here:
https://issues.apache.org/jira/browse/COMPRESS-453   
https://github.com/tensorflow/tensorflow/issues/16862#issuecomment-388321934

Using Java binary from `https://github.com/AdoptOpenJDK/openjdk8-openj9-releases/releases/download/jdk8u162-b12_openj9-0.8.0/OpenJDK8-OPENJ9_s390x_Linux_jdk8u162-b12_openj9-0.8.0.tar.gz`
```
java -version:

openjdk version "1.8.0_162"
OpenJDK Runtime Environment (build 1.8.0_162-b12)
Eclipse OpenJ9 VM (build openj9-0.8.0, JRE 1.8.0 Linux s390x-64 Compressed References 20180315_97 (JIT enabled, AOT enabled)
OpenJ9   - e24e8aa9
OMR      - 3e8296b4
JCL      - ee1e77df1d based on jdk8u162-b12)
```

Could someone please help in resolving the issue?
Any pointers would be helpful.

**Comment by tellison** [comment]
Hi @namrata-ibm 

Hard to tell from the limited info in the error.

Can you clarify:
> I have verified that the build with OpenJDK 8 works.

Which build works OK for you?  From that we might start to narrow down wether it is a classes of JVM related issue, and then be able to ask you for more specific debug information.

**Comment by namrata-ibm** [comment]
@tellison , Thank you for your response.

I am able to build TensorFlow with Openjdk-8-jdk installed from Ubuntu repository.
```
java -version:  
openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-8u171-b11-0ubuntu0.16.04.1-b11)
OpenJDK 64-Bit Zero VM (build 25.171-b11, interpreted mode)
```
Build had completed with `Openjdk-8-jdk` with earlier minor versions too like `8u162`/ `8u151`.

Here are Jenkins jobs for reference:
1. With AdoptOpenJDK(Failing): https://ibmz-ci.osuosl.org/job/TensorFlow_IBMZ_CI/73/consoleFull
2. With OpenJDK(Passing): https://ibmz-ci.osuosl.org/job/TensorFlow_IBMZ_CI/74/consoleFull

Let me know if any other information is needed.

**Comment by namrata-ibm** [comment]
After doing some more analysis on this issue, have below observations for further analysis:
While the nasm package is uncompressed using `Apache Commons Compress`, JIT shows some erroneous behavior as below:
For code snippet 
```
System.err.println("before loop s: " + s + ", lastShadow: " + lastShadow);
while (s-- >= 0) {
    ll8[++lastShadow] = ch;
}
System.err.println("after loop s: " + s + ", lastShadow: " + lastShadow);
```
when s=5, while loop should execute 6 times and exit. However due to some bug in JIT, it gets executed 7 times, as per below log output:
```
before loop s: 5, lastShadow: 899994
after loop s: -2, lastShadow: 900001
```
More reference in : https://issues.apache.org/jira/browse/COMPRESS-453

Attaching logs for OpenJDK as well as AdoptOpenJDK for comparison.
It can be seen from the log that, it first seems to work OK (lastShadow should get incremented by s + 1) but starts to go wrong at one point in time( from line number 599184 in the logs below).

[TestLog__AdoptJDK.txt](https://github.com/AdoptOpenJDK/openjdk8-openj9-releases/files/2044994/TestLog__AdoptJDK.txt)

[TestLog__OpenJDK_truncated.txt](https://github.com/AdoptOpenJDK/openjdk8-openj9-releases/files/2045040/TestLog__OpenJDK_truncated.txt)

**Comment by karianna** [comment]
This issue was moved to AdoptOpenJDK/openjdk-build#486
